site_name: Appflix
theme:
    name: 'material'
    custom_dir: docs-source/overrides
    logo: 'logo.svg'
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          accent: lime
          primary: red
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
plugins:
    - i18n:
          default_language: de
          languages:
              de: Deutsch
              en: English
          nav_translations:
              de:
                  Documentation: App Dokumentation
                  Imprint: Impressum
                  OrderManagement: Bestellverwaltung
                  QuickSetup: Schnelleinrichtung
                  StoreConfiguration: Shop Konfiguration
              en:
                  Documentation: App Documentation
                  Imprint: Imprint
                  OrderManagement: Order Management
                  QuickSetup: Quick Setup
                  StoreConfiguration: Store Configuration
              nl:
                  Documentation: App Documentatie
                  Imprint: Afdruk
              zh:
                  Documentation: 应用程序文档
                  Imprint: 版本说明
    - search
docs_dir: docs-source
site_dir: docs-html
site_url: 'https://docs.app-flix.de'
extra:
    consent:
        title: Cookie consent
        description: >
            We use cookies to recognize your repeated visits and preferences, as well
            as to measure the effectiveness of our documentation and whether users
            find what they're searching for. With your consent, you're helping us to
            make our documentation better.
        cookies:
            matomo: Matomo Tracker
nav:
    - Home: index.md
    - Foundation:
          - 'foundation/index.md'
          - 'foundation/addons/index.md'
          - 'foundation/demo-installer/index.md'
          - 'foundation/animation/index.md'
          - 'foundation/cms-animation/index.md'
    - DeliveryWare:
        - 'deliveryware/index.md'
        - 'deliveryware/faq/index.md'
        - QuickSetup:
            - 'deliveryware/installation/index.md'
            - 'deliveryware/demo-assistant/index.md'
        - StoreConfiguration:
            - 'deliveryware/shops/index.md'
            - 'deliveryware/mail-templates/index.md'
            - 'deliveryware/options/index.md'
            - 'deliveryware/ingredients/index.md'
            - 'deliveryware/badges/index.md'
        - OrderManagement:
            - 'deliveryware/dashboard/index.md'
            - 'deliveryware/printers/index.md'
            - 'deliveryware/gps-tracking/index.md'
        - 'deliveryware/theme/index.md'
        - 'deliveryware/changelog/index.md'
    - Studygood:
          - 'studygood/index.md'
          - 'studygood/faq/index.md'
          - Schnelleinrichtung:
                - Installation: 'studygood/installation/index.md'
                - Demo Daten anlegen: 'studygood/demo-assistant/index.md'
          - Kurs Konfiguration:
                - Kursverwaltung: 'studygood/course/index.md'
                - Kapitel: 'studygood/chapter/index.md'
                - Lektionen: 'studygood/lesson/index.md'
                - Produkt Konfiguration: 'studygood/product/index.md'
                - Tutor: 'studygood/tutor/index.md'
                - Board: 'studygood/board/index.md'
    - Kleinanzeigen:
        - 'customer-market/index.md'
        - 'customer-market/faq/index.md'
        - QuickSetup:
            - 'customer-market/installation/index.md'
            - 'customer-market/demo-assistant/index.md'
        - 'customer-market/ad-type/index.md'
        - 'customer-market/ad/index.md'
        - 'customer-market/cms/index.md'
    - Shopware Store: 'https://store.shopware.com/appflix-ug.html'
    - Kontakt: 'mailto:info@app-flix.de'
    - Impressum: 'imprint/index.md'
