site_name: DeliveryWare Shopware 6 App Dokumentation
edit_uri: blob/master/docs-source/
theme:
    name: 'material'
docs_dir: docs-source
site_dir: docs-html
extra_css:
    - 'jquery.fancybox.min.css'
    - 'extra.css'
extra_javascript:
    - 'jquery-3.5.0.slim.min.js'
    - 'jquery.fancybox.min.js'
    - 'extra.js'

nav:
    - Start: 'index.md'
    - Häufig gestellte Fragen (FAQ): 'faq/index.md'
    - Store Präsentation: '_store/index.md'
    - Schnelleinrichtung:
        - Installation: 'installation/index.md'
        - Demo Daten anlegen: 'demo-assistant/index.md'
        - Migrations Tool: 'migration/index.md'
    - Shop Konfiguration:
        - Shops und Verkaufstellen: 'shops/index.md'
        - E-Mail Templates: 'mail-templates/index.md'
        - Konfigurator (Optionen): 'options/index.md'
        - Inhaltsstoffe: 'ingredients/index.md'
        - Badges (Hervorheben): 'badges/index.md'
    - Theme Konfiguration: 'theme/index.md'
    - Bestellverwaltung:
        - Dashboard: 'dashboard/index.md'
        - Bon Drucker Einrichtung: 'printers/index.md'
        - GPS Tracking: 'gps-tracking/index.md'

    - Shopware Store: 'https://store.shopware.com/appflix.html'
    - Kontakt: 'mailto:info@app-flix.de'
    - Impressum: 'imprint/index.md'
